// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB3-x5JzLhGsutYnVwRcrWjHlrMuKzyxg',
    appId: '1:662959309380:web:8dbabebeafdc2d9e90b211',
    messagingSenderId: '662959309380',
    projectId: 'my-fragrance-app-4c75d',
    authDomain: 'my-fragrance-app-4c75d.firebaseapp.com',
    storageBucket: 'my-fragrance-app-4c75d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ20GnPAhmCApOJxFgp7MA8epRAivt38U',
    appId: '1:662959309380:android:b9d023f699c9f91b90b211',
    messagingSenderId: '662959309380',
    projectId: 'my-fragrance-app-4c75d',
    storageBucket: 'my-fragrance-app-4c75d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDohiIELf_5DnszZ2r2fAajrcJPav02rIs',
    appId: '1:662959309380:ios:f4b6bec7628c84e690b211',
    messagingSenderId: '662959309380',
    projectId: 'my-fragrance-app-4c75d',
    storageBucket: 'my-fragrance-app-4c75d.firebasestorage.app',
    iosBundleId: 'com.example.myFragrance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDohiIELf_5DnszZ2r2fAajrcJPav02rIs',
    appId: '1:662959309380:ios:f4b6bec7628c84e690b211',
    messagingSenderId: '662959309380',
    projectId: 'my-fragrance-app-4c75d',
    storageBucket: 'my-fragrance-app-4c75d.firebasestorage.app',
    iosBundleId: 'com.example.myFragrance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB3-x5JzLhGsutYnVwRcrWjHlrMuKzyxg',
    appId: '1:662959309380:web:14524e86a4eb999f90b211',
    messagingSenderId: '662959309380',
    projectId: 'my-fragrance-app-4c75d',
    authDomain: 'my-fragrance-app-4c75d.firebaseapp.com',
    storageBucket: 'my-fragrance-app-4c75d.firebasestorage.app',
  );
}
